<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>CRUD MVC</title>
    </head>
    <body>
        <header>
           <nav>
                <ul>
                    <li
                        <a href="index.php?route=list">Liste des utilisateurs</a>
                    </li>
                    <li>
                        <a href="index.php?route=show_user">Afficher un utilisateur</a>
                    </li>
                    <li>
                        <a href="index.php?route=create_user">Créer un utilisateur</a>
                    </li>
                    <li>
                        <a href="index.php?route=update_user">Modifier un utilisateur</a>
                    </li>
                    <li>
                        <a href="index.php?route=check_create_user">Check création</a>
                    </li>
                    <li>
                        <a href="index.php?route=check_update_user">Check mise à jour</a>
                    </li>
                    <li>
                        <a href="index.php?route=delete_user">Supprimer un utilisateur</a>
                    </li>
                </ul>
            </nav>

        </header>
            <?php
                // Charger le template correspondant
                if (isset($route)) {
                    require "templates/$route.phtml";
                }
?>

</body>
</html>
