<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>CRUD MVC</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.php">Liste des utilisateurs</a>
                </li>
                <li><a href="index.php?route=create_user">Créer un utilisateur</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <?php
        // Charger le template correspondant
        if (isset($route)) {
            require "templates/$route.phtml";
        }
        ?>
    </main>
</body>
</html>
