<main>
    <h1>Créer un nouvel utilisateur</h1>
    <form action="index.php?route=check_create_user" method="post">
        <div>
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
        </div>

        <div>
            <label for="first_name">Prénom :</label>
            <input type="text" id="first_name" name="first_name" required>
        </div>

        <div>
            <label for="last_name">Nom :</label>
            <input type="text" id="last_name" name="last_name" required>
        </div>

        <button type="submit">Ajouter</button>
    </form>
</main>
